			
INSERT INTO tb_status(id_status,status) values(	1,	'Finished'	);
INSERT INTO tb_status(id_status,status) values(	2,	'Disqualified'	);
INSERT INTO tb_status(id_status,status) values(	3,	'Accident'	);
INSERT INTO tb_status(id_status,status) values(	4,	'Collision'	);
INSERT INTO tb_status(id_status,status) values(	5,	'Engine'	);
INSERT INTO tb_status(id_status,status) values(	6,	'Gearbox'	);
INSERT INTO tb_status(id_status,status) values(	7,	'Transmission'	);
INSERT INTO tb_status(id_status,status) values(	8,	'Clutch'	);
INSERT INTO tb_status(id_status,status) values(	9,	'Hydraulics'	);
INSERT INTO tb_status(id_status,status) values(	10,	'Electrical'	);
INSERT INTO tb_status(id_status,status) values(	11,	'+1 Lap'	);
INSERT INTO tb_status(id_status,status) values(	12,	'+2 Laps'	);
INSERT INTO tb_status(id_status,status) values(	13,	'+3 Laps'	);
INSERT INTO tb_status(id_status,status) values(	14,	'+4 Laps'	);
INSERT INTO tb_status(id_status,status) values(	15,	'+5 Laps'	);
INSERT INTO tb_status(id_status,status) values(	16,	'+6 Laps'	);
INSERT INTO tb_status(id_status,status) values(	17,	'+7 Laps'	);
INSERT INTO tb_status(id_status,status) values(	18,	'+8 Laps'	);
INSERT INTO tb_status(id_status,status) values(	19,	'+9 Laps'	);
INSERT INTO tb_status(id_status,status) values(	20,	'Spun off'	);
INSERT INTO tb_status(id_status,status) values(	21,	'Radiator'	);
INSERT INTO tb_status(id_status,status) values(	22,	'Suspension'	);
INSERT INTO tb_status(id_status,status) values(	23,	'Brakes'	);
INSERT INTO tb_status(id_status,status) values(	24,	'Differential'	);
INSERT INTO tb_status(id_status,status) values(	25,	'Overheating'	);
INSERT INTO tb_status(id_status,status) values(	26,	'Mechanical'	);
INSERT INTO tb_status(id_status,status) values(	27,	'Tyre'	);
INSERT INTO tb_status(id_status,status) values(	28,	'Driver Seat'	);
INSERT INTO tb_status(id_status,status) values(	29,	'Puncture'	);
INSERT INTO tb_status(id_status,status) values(	30,	'Driveshaft'	);
INSERT INTO tb_status(id_status,status) values(	31,	'Retired'	);
INSERT INTO tb_status(id_status,status) values(	32,	'Fuel pressure'	);
INSERT INTO tb_status(id_status,status) values(	33,	'Front wing'	);
INSERT INTO tb_status(id_status,status) values(	34,	'Water pressure'	);
INSERT INTO tb_status(id_status,status) values(	35,	'Refuelling'	);
INSERT INTO tb_status(id_status,status) values(	36,	'Wheel'	);
INSERT INTO tb_status(id_status,status) values(	37,	'Throttle'	);
INSERT INTO tb_status(id_status,status) values(	38,	'Steering'	);
INSERT INTO tb_status(id_status,status) values(	39,	'Technical'	);
INSERT INTO tb_status(id_status,status) values(	40,	'Electronics'	);
INSERT INTO tb_status(id_status,status) values(	41,	'Broken wing'	);
INSERT INTO tb_status(id_status,status) values(	42,	'Heat shield fire'	);
INSERT INTO tb_status(id_status,status) values(	43,	'Exhaust'	);
INSERT INTO tb_status(id_status,status) values(	44,	'Oil leak'	);
INSERT INTO tb_status(id_status,status) values(	45,	'+11 Laps'	);
INSERT INTO tb_status(id_status,status) values(	46,	'Wheel rim'	);
INSERT INTO tb_status(id_status,status) values(	47,	'Water leak'	);
INSERT INTO tb_status(id_status,status) values(	48,	'Fuel pump'	);
INSERT INTO tb_status(id_status,status) values(	49,	'Track rod'	);
INSERT INTO tb_status(id_status,status) values(	50,	'+17 Laps'	);
INSERT INTO tb_status(id_status,status) values(	51,	'Oil pressure'	);
INSERT INTO tb_status(id_status,status) values(	128,	'+42 Laps'	);
INSERT INTO tb_status(id_status,status) values(	53,	'+13 Laps'	);
INSERT INTO tb_status(id_status,status) values(	54,	'Withdrew'	);
INSERT INTO tb_status(id_status,status) values(	55,	'+12 Laps'	);
INSERT INTO tb_status(id_status,status) values(	56,	'Engine fire'	);
INSERT INTO tb_status(id_status,status) values(	129,	'Engine misfire'	);
INSERT INTO tb_status(id_status,status) values(	58,	'+26 Laps'	);
INSERT INTO tb_status(id_status,status) values(	59,	'Tyre puncture'	);
INSERT INTO tb_status(id_status,status) values(	60,	'Out of fuel'	);
INSERT INTO tb_status(id_status,status) values(	61,	'Wheel nut'	);
INSERT INTO tb_status(id_status,status) values(	62,	'Not classified'	);
INSERT INTO tb_status(id_status,status) values(	63,	'Pneumatics'	);
INSERT INTO tb_status(id_status,status) values(	64,	'Handling'	);
INSERT INTO tb_status(id_status,status) values(	65,	'Rear wing'	);
INSERT INTO tb_status(id_status,status) values(	66,	'Fire'	);
INSERT INTO tb_status(id_status,status) values(	67,	'Wheel bearing'	);
INSERT INTO tb_status(id_status,status) values(	68,	'Physical'	);
INSERT INTO tb_status(id_status,status) values(	69,	'Fuel system'	);
INSERT INTO tb_status(id_status,status) values(	70,	'Oil line'	);
INSERT INTO tb_status(id_status,status) values(	71,	'Fuel rig'	);
INSERT INTO tb_status(id_status,status) values(	72,	'Launch control'	);
INSERT INTO tb_status(id_status,status) values(	73,	'Injured'	);
INSERT INTO tb_status(id_status,status) values(	74,	'Fuel'	);
INSERT INTO tb_status(id_status,status) values(	75,	'Power loss'	);
INSERT INTO tb_status(id_status,status) values(	76,	'Vibrations'	);
INSERT INTO tb_status(id_status,status) values(	77,	'107% Rule'	);
INSERT INTO tb_status(id_status,status) values(	78,	'Safety'	);
INSERT INTO tb_status(id_status,status) values(	79,	'Drivetrain'	);
INSERT INTO tb_status(id_status,status) values(	80,	'Ignition'	);
INSERT INTO tb_status(id_status,status) values(	81,	'Did not qualify'	);
INSERT INTO tb_status(id_status,status) values(	82,	'Injury'	);
INSERT INTO tb_status(id_status,status) values(	83,	'Chassis'	);
INSERT INTO tb_status(id_status,status) values(	84,	'Battery'	);
INSERT INTO tb_status(id_status,status) values(	85,	'Stalled'	);
INSERT INTO tb_status(id_status,status) values(	86,	'Halfshaft'	);
INSERT INTO tb_status(id_status,status) values(	87,	'Crankshaft'	);
INSERT INTO tb_status(id_status,status) values(	88,	'+10 Laps'	);
INSERT INTO tb_status(id_status,status) values(	89,	'Safety concerns'	);
INSERT INTO tb_status(id_status,status) values(	90,	'Not restarted'	);
INSERT INTO tb_status(id_status,status) values(	91,	'Alternator'	);
INSERT INTO tb_status(id_status,status) values(	92,	'Underweight'	);
INSERT INTO tb_status(id_status,status) values(	93,	'Safety belt'	);
INSERT INTO tb_status(id_status,status) values(	94,	'Oil pump'	);
INSERT INTO tb_status(id_status,status) values(	95,	'Fuel leak'	);
INSERT INTO tb_status(id_status,status) values(	96,	'Excluded'	);
INSERT INTO tb_status(id_status,status) values(	97,	'Did not prequalify'	);
INSERT INTO tb_status(id_status,status) values(	98,	'Injection'	);
INSERT INTO tb_status(id_status,status) values(	99,	'Distributor'	);
INSERT INTO tb_status(id_status,status) values(	100,	'Driver unwell'	);
INSERT INTO tb_status(id_status,status) values(	101,	'Turbo'	);
INSERT INTO tb_status(id_status,status) values(	102,	'CV joint'	);
INSERT INTO tb_status(id_status,status) values(	103,	'Water pump'	);
INSERT INTO tb_status(id_status,status) values(	104,	'Fatal accident'	);
INSERT INTO tb_status(id_status,status) values(	105,	'Spark plugs'	);
INSERT INTO tb_status(id_status,status) values(	106,	'Fuel pipe'	);
INSERT INTO tb_status(id_status,status) values(	107,	'Eye injury'	);
INSERT INTO tb_status(id_status,status) values(	108,	'Oil pipe'	);
INSERT INTO tb_status(id_status,status) values(	109,	'Axle'	);
INSERT INTO tb_status(id_status,status) values(	110,	'Water pipe'	);
INSERT INTO tb_status(id_status,status) values(	111,	'+14 Laps'	);
INSERT INTO tb_status(id_status,status) values(	112,	'+15 Laps'	);
INSERT INTO tb_status(id_status,status) values(	113,	'+25 Laps'	);
INSERT INTO tb_status(id_status,status) values(	114,	'+18 Laps'	);
INSERT INTO tb_status(id_status,status) values(	115,	'+22 Laps'	);
INSERT INTO tb_status(id_status,status) values(	116,	'+16 Laps'	);
INSERT INTO tb_status(id_status,status) values(	117,	'+24 Laps'	);
INSERT INTO tb_status(id_status,status) values(	118,	'+29 Laps'	);
INSERT INTO tb_status(id_status,status) values(	119,	'+23 Laps'	);
INSERT INTO tb_status(id_status,status) values(	120,	'+21 Laps'	);
INSERT INTO tb_status(id_status,status) values(	121,	'Magneto'	);
INSERT INTO tb_status(id_status,status) values(	122,	'+44 Laps'	);
INSERT INTO tb_status(id_status,status) values(	123,	'+30 Laps'	);
INSERT INTO tb_status(id_status,status) values(	124,	'+19 Laps'	);
INSERT INTO tb_status(id_status,status) values(	125,	'+46 Laps'	);
INSERT INTO tb_status(id_status,status) values(	126,	'Supercharger'	);
INSERT INTO tb_status(id_status,status) values(	127,	'+20 Laps'	);
INSERT INTO tb_status(id_status,status) values(	130,	'Collision damage'	);
INSERT INTO tb_status(id_status,status) values(	131,	'Power Unit'	);
INSERT INTO tb_status(id_status,status) values(	132,	'ERS'	);
INSERT INTO tb_status(id_status,status) values(	133,	'+49 Laps'	);
INSERT INTO tb_status(id_status,status) values(	134,	'+38 Laps'	);
INSERT INTO tb_status(id_status,status) values(	135,	'Brake duct'	);
INSERT INTO tb_status(id_status,status) values(	136,	'Seat'	);
INSERT INTO tb_status(id_status,status) values(	137,	'Damage'	);
INSERT INTO tb_status(id_status,status) values(	138,	'Debris'	);
INSERT INTO tb_status(id_status,status) values(	139,	'Illness'	);
