					
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	1	,'Albert Park Grand Prix Circuit',	'Melbourne',	'Australia'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	2	,'Sepang International Circuit',	'Kuala Lumpur',	'Malaysia'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	3	,'Bahrain International Circuit',	'Sakhir',	'Bahrain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	4	,'Circuit de Barcelona-Catalunya',	'MontmelÃ³',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	5	,'Istanbul Park',	'Istanbul',	'Turkey'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	6	,'Circuit de Monaco',	'Monte-Carlo',	'Monaco'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	7	,'Circuit Gilles Villeneuve',	'Montreal',	'Canada'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	8	,'Circuit de Nevers Magny-Cours',	'Magny Cours',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	9	,'Silverstone Circuit',	'Silverstone',	'UK'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	10	,'Hockenheimring',	'Hockenheim',	'Germany'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	11	,'Hungaroring',	'Budapest',	'Hungary'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	12	,'Valencia Street Circuit',	'Valencia',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	13	,'Circuit de Spa-Francorchamps',	'Spa',	'Belgium'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	14	,'Autodromo Nazionale di Monza',	'Monza',	'Italy'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	15	,'Marina Bay Street Circuit',	'Marina Bay',	'Singapore'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	16	,'Fuji Speedway',	'Oyama',	'Japan'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	17	,'Shanghai International Circuit',	'Shanghai',	'China'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	18	,'AutÃ³dromo JosÃ© Carlos Pace',	'SÃ£o Paulo',	'Brazil'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	19	,'Indianapolis Motor Speedway',	'Indianapolis',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	20	,'NÃ¼rburgring',	'NÃ¼rburg',	'Germany'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	21	,'Autodromo Enzo e Dino Ferrari',	'Imola',	'Italy'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	22	,'Suzuka Circuit',	'Suzuka',	'Japan'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	23	,'A1-Ring',	'Spielburg',	'Austria'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	24	,'Yas Marina Circuit',	'Abu Dhabi',	'UAE'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	25	,'AutÃ³dromo Juan y Oscar GÃ¡lvez',	'Buenos Aires',	'Argentina'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	26	,'Circuito de Jerez',	'Jerez de la Frontera',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	27	,'AutÃ³dromo do Estoril',	'Estoril',	'Portugal'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	28	,'Okayama International Circuit',	'Okayama',	'Japan'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	29	,'Adelaide Street Circuit',	'Adelaide',	'Australia'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	30	,'Kyalami',	'Midrand',	'South Africa'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	31	,'Donington Park',	'Castle Donington',	'UK'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	32	,'AutÃ³dromo Hermanos RodrÃ­guez',	'Mexico City',	'Mexico'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	33	,'Phoenix street circuit',	'Phoenix',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	34	,'Circuit Paul Ricard',	'Le Castellet',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	35	,'Korean International Circuit',	'Yeongam County',	'Korea'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	36	,'AutÃ³dromo Internacional Nelson Piquet',	'Rio de Janeiro',	'Brazil'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	37	,'Detroit Street Circuit',	'Detroit',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	38	,'Brands Hatch',	'Kent',	'UK'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	39	,'Circuit Park Zandvoort',	'Zandvoort',	'Netherlands'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	40	,'Zolder',	'Heusden-Zolder',	'Belgium'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	41	,'Dijon-Prenois',	'Dijon',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	42	,'Fair Park',	'Dallas',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	43	,'Long Beach',	'California',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	44	,'Las Vegas Street Circuit',	'Nevada',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	45	,'Jarama',	'Madrid',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	46	,'Watkins Glen',	'New York State',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	47	,'Scandinavian Raceway',	'Anderstorp',	'Sweden'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	48	,'Mosport International Raceway',	'Ontario',	'Canada'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	49	,'MontjuÃ¯c',	'Barcelona',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	50	,'Nivelles-Baulers',	'Brussels',	'Belgium'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	51	,'Charade Circuit',	'Clermont-Ferrand',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	52	,'Circuit Mont-Tremblant',	'Quebec',	'Canada'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	53	,'Rouen-Les-Essarts',	'Rouen',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	54	,'Le Mans',	'Le Mans',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	55	,'Reims-Gueux',	'Reims',	'France'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	56	,'Prince George Circuit',	'Eastern Cape Province',	'South Africa'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	57	,'Zeltweg',	'Styria',	'Austria'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	58	,'Aintree',	'Liverpool',	'UK'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	59	,'Circuito da Boavista',	'Oporto',	'Portugal'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	60	,'Riverside International Raceway',	'California',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	61	,'AVUS',	'Berlin',	'Germany'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	62	,'Monsanto Park Circuit',	'Lisbon',	'Portugal'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	63	,'Sebring International Raceway',	'Florida',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	64	,'Ain Diab',	'Casablanca',	'Morocco'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	65	,'Pescara Circuit',	'Pescara',	'Italy'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	66	,'Circuit Bremgarten',	'Bern',	'Switzerland'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	67	,'Circuit de Pedralbes',	'Barcelona',	'Spain'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	68	,'Buddh International Circuit',	'Uttar Pradesh',	'India'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	69	,'Circuit of the Americas',	'Austin',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	70	,'Red Bull Ring',	'Spielburg',	'Austria'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	71	,'Sochi Autodrom',	'Sochi',	'Russia'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	72	,'Port Imperial Street Circuit',	'New Jersey',	'USA'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	73	,'Baku City Circuit',	'Baku',	'Azerbaijan'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	74	,'Hanoi Street Circuit',	'Hanoi',	'Vietnam'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	75	,'AutÃ³dromo Internacional do Algarve',	'PortimÃ£o',	'Portugal'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	76	,'Autodromo Internazionale del Mugello',	'Mugello',	'Italy'	);
INSERT INTO tb_circuito(id_circuito,nome_circuito,localidade_circuito,pais_circuito) values (	77	,'Jeddah Street Circuit',	'Jeddah',	'Saudi Arabia'	);
